/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.geektrust.lengaburu.war;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    App app = new App();

    @Test
    public void test01() {
        assertEquals("WINS 52H 50E 10AT 3SG", invokeApp("FELICORNIA_ATTACK 100H 101E 20AT 5SG"));
    }

    @Test
    public void test02() {
        assertEquals("WINS 75H 50E 10AT 5SG", invokeApp("FELICORNIA_ATTACK 150H 96E 26AT 8SG"));
    }

    @Test
    public void test03() {
        assertEquals("LOSES 100H 38E 10AT 5SG", invokeApp("FELICORNIA_ATTACK 250H 50E 20AT 15SG"));
    }

    private String invokeApp(String command) {
        return app.processInputFromCli(new String[]{command});
    }
}
