/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.geektrust.lengaburu.war;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    App app = new App();

    @Test
    public void test01() {
        assertEquals("WINS 52H 50E 10AT 3SG", app.processInputFromCli(new String[]{"FALICORNIA_ATTACK 100H 101E 20AT 5SG"}));
    }
}
